### ISSUE TITLE
Size issues for Android

### ISSUE THREAD

**Issue by EsmerlinJM** [EsmerlinJM/Card-Wallet-App#2]
Because it is developed for IOS the app has size problems in Android.

**Comment by Levi-Lesches** [comment]
Hi! This app looks interesting, would you like some help?

**Comment by EsmerlinJM** [comment]
Thanks! A help is always useful, the problem I just found is that of the sizes and since I didn't have time to add it to Android.

**Comment by Levi-Lesches** [comment]
Ok, I'll look into it
